config/routes.rb
Rails.application.routes.draw do

  resources :price_plans
  get 'welcome/index'

  get 'welcome/setAdmin'

  get 'welcome/unSetAdmin'

  get 'welcome/createdog'

  post 'welcome/addrego'

  get 'welcome/report'

  devise_for :users
  resources :regos
  resources :breeds
  resources :dogs
  resources :owners

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DogRegoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
</head>
<body>

<div class="container">
	<%= link_to "Home", root_path %>
	<% if user_signed_in? %>
	  <% if current_user.admin? %>
	    <%= link_to 'Owners', owners_path %>
	    <%= link_to 'Breeds', breeds_path %>
	    <%= link_to 'Dogs', dogs_path %>
	    <%= link_to 'Registrations', regos_path %>
	    <%= link_to 'Price Plans', price_plans_path %>
	    <%= link_to 'Report', '/welcome/report' %>
	    <%= link_to 'Unmake admin', controller: 'welcome', action: 'unSetAdmin' %>
	  <% else %>
	    <%= link_to 'Make admin', controller: 'welcome', action: 'setAdmin' %>
	  <% end %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
	<% if notice %>
	  <p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
	  <p class="alert alert-danger"><%= alert %></p>
	<% end %>

<%= yield %>

</div>
</body>
</html>